### PR TITLE
Updated for November 2019 update

### PR DESCRIPTION
**Pull request by polivilas**
Runs once again. yay.
NOTE: I haven't added a compiled version.

### CODE REVIEW

**Comment by Leystryku** [comment]
Thanks for updating it :)
Could you please also add a compiled version?
As far as I'm aware the only way to get the compiled version is now the repository so if you updated the code, you should update the compiled version accordingly.

Thanks!

**Comment by polivilas** [comment]
Built!

**Comment by Leystryku** [comment]
Thank you!
Once I've reverse engineered your compiled binary to confirm there are no security issues I'll merge!

**Comment by Leystryku** [comment]
Alright, checked your binary in IDA. Merging!

**Pull request merged**
